// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myntra_clone_api.Data;

#nullable disable

namespace myntra_clone_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240302094429_added promotions table")]
    partial class addedpromotionstable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("myntra_clone_api.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("myntra_clone_api.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainCategory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("myntra_clone_api.Models.MainCategory", b =>
                {
                    b.Property<int>("MainCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MainCategoryId"));

                    b.Property<string>("MainCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MainCategoryId");

                    b.ToTable("MainCategories");
                });

            modelBuilder.Entity("myntra_clone_api.Models.ProductSpecification", b =>
                {
                    b.Property<int>("SpecificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecificationId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SpecificationKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificationValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpecificationId");

                    b.ToTable("ProductSpecifications");
                });

            modelBuilder.Entity("myntra_clone_api.Models.Products", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountedPrice")
                        .HasColumnType("float");

                    b.Property<bool>("IsCOD")
                        .HasColumnType("bit");

                    b.Property<string>("MainCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialCare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OriginalPrice")
                        .HasColumnType("float");

                    b.Property<string>("ProductDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Sellers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SizeFit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCategory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("myntra_clone_api.Models.Promotions", b =>
                {
                    b.Property<int>("PromoionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromoionId"));

                    b.Property<string>("PromotionBrands")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromotionCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromotionDiscount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromotionImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromotionMainCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromotionSubCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromotionType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PromoionId");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            PromoionId = 29,
                            PromotionBrands = "",
                            PromotionCategory = "",
                            PromotionDiscount = "50",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_163,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/babe0d1a-b7fe-4b36-8a98-b275523963721690787339222-Shop-By-Category_HP-4_14.jpg",
                            PromotionMainCategory = "Kids",
                            PromotionSubCategory = "",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 30,
                            PromotionBrands = "",
                            PromotionCategory = "Footwear",
                            PromotionDiscount = "50",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_163,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/3c2095db-905a-4346-9712-2fac7bcbbbd71690787339011-Shop-By-Category_HP-4_15.jpg",
                            PromotionMainCategory = "Men",
                            PromotionSubCategory = "",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 31,
                            PromotionBrands = "",
                            PromotionCategory = "Footwear",
                            PromotionDiscount = "40",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_163,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/c1c8027f-1a22-4a0b-8be2-848edab298cf1690787339044-Shop-By-Category_HP-4_16.jpg",
                            PromotionMainCategory = "Women",
                            PromotionSubCategory = "",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 32,
                            PromotionBrands = "",
                            PromotionCategory = "",
                            PromotionDiscount = "40",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_163,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/278917b5-1658-4c2c-b122-f623b1d909701690787339290-Shop-By-Category_HP-4_17.jpg",
                            PromotionMainCategory = "Men",
                            PromotionSubCategory = "Wallets,Belts",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 33,
                            PromotionBrands = "",
                            PromotionCategory = "Topwear",
                            PromotionDiscount = "40",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_163,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/6c53770e-b7b2-466a-b36e-a0b2bff1a7591690787339109-Shop-By-Category_HP-4_18.jpg",
                            PromotionMainCategory = "Men",
                            PromotionSubCategory = "Formal Shirts",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 34,
                            PromotionBrands = "",
                            PromotionCategory = "Indian & Festive Wear",
                            PromotionDiscount = "60",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_163,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/54852b61-90d6-484a-84c9-a8560247ffc21690787339307-Shop-By-Category_HP-4_19.jpg",
                            PromotionMainCategory = "Men",
                            PromotionSubCategory = "",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 35,
                            PromotionBrands = "",
                            PromotionCategory = "Home Décor",
                            PromotionDiscount = "40",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_163,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/5d78afb6-38bb-43bd-bc67-1e4f6026b6ae1690787339327-Shop-By-Category_HP-4_20.jpg",
                            PromotionMainCategory = "Home & Living",
                            PromotionSubCategory = "",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 36,
                            PromotionBrands = "",
                            PromotionCategory = "Handbags, Bags & Wallets",
                            PromotionDiscount = "40",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_163,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/90dcb992-9fb4-4208-8249-aa1a01b2851d1690787339476-Shop-By-Category_HP-4_21.jpg",
                            PromotionMainCategory = "Women",
                            PromotionSubCategory = "",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 37,
                            PromotionBrands = "",
                            PromotionCategory = "Gadgets",
                            PromotionDiscount = "70",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_163,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/e4fcb9f0-f79a-41b7-b7b2-8828bb6e95e61690787339426-Shop-By-Category_HP-4_22.jpg",
                            PromotionMainCategory = "Men",
                            PromotionSubCategory = "",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 38,
                            PromotionBrands = "",
                            PromotionCategory = "Jewellery",
                            PromotionDiscount = "80",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_163,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/66882f76-0bbe-4741-8890-0426695e09131690787339238-Shop-By-Category_HP-4_23.jpg",
                            PromotionMainCategory = "Women",
                            PromotionSubCategory = "",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 39,
                            PromotionBrands = "",
                            PromotionCategory = "Plus Size",
                            PromotionDiscount = "60",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_163,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/6aa501b3-ce05-48f5-96fe-ecb64682dbc71690787339409-Shop-By-Category_HP-4_24.jpg",
                            PromotionMainCategory = "Women",
                            PromotionSubCategory = "",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 40,
                            PromotionBrands = "",
                            PromotionCategory = "Plus Size",
                            PromotionDiscount = "60",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_163,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/b6e15609-4f52-44db-80c1-2a955fd4ac6e1690787339341-Shop-By-Category_HP-4_25.jpg",
                            PromotionMainCategory = "Men",
                            PromotionSubCategory = "",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 41,
                            PromotionBrands = "",
                            PromotionCategory = "Smart Wearables",
                            PromotionDiscount = "80",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_163,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/7916724b-be74-4920-b58d-ada0617cdee91690787339392-Shop-By-Category_HP-4_26.jpg",
                            PromotionMainCategory = "Men",
                            PromotionSubCategory = "",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 42,
                            PromotionBrands = "",
                            PromotionCategory = "Sleepwear & Loungewear",
                            PromotionDiscount = "30",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_163,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/5c541739-5c23-4846-a875-f19a170cea151690787339460-Shop-By-Category_HP-4_27.jpg",
                            PromotionMainCategory = "Women",
                            PromotionSubCategory = "",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 43,
                            PromotionBrands = "",
                            PromotionCategory = "Western Wear",
                            PromotionDiscount = "40",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_163,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/76932333-b792-4f54-983c-45aaf70e04ef1690787338936-Shop-By-Category_HP-4_28.jpg",
                            PromotionMainCategory = "Women",
                            PromotionSubCategory = "Blazers & Waistcoats",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 44,
                            PromotionBrands = "",
                            PromotionCategory = "Sunglasses & Frames",
                            PromotionDiscount = "80",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_163,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/a351ad62-c1d1-4bb4-9967-d3966f8446521690787338974-Shop-By-Category_HP-4_29.jpg",
                            PromotionMainCategory = "Men",
                            PromotionSubCategory = "",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 45,
                            PromotionBrands = "",
                            PromotionCategory = "Topwear",
                            PromotionDiscount = "40",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_163,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/130ceab4-ac68-42c5-a9f4-478ba7f903db1690787339061-Shop-By-Category_HP-4_30.jpg",
                            PromotionMainCategory = "Men",
                            PromotionSubCategory = "Formal Shirts",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 46,
                            PromotionBrands = "",
                            PromotionCategory = "Western Wear",
                            PromotionDiscount = "40",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_163,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/cda4c195-22c1-4e11-a9dc-4728d69c3f2b1690787338956-Shop-By-Category_HP-4_31.jpg",
                            PromotionMainCategory = "Women",
                            PromotionSubCategory = "Dresses",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 47,
                            PromotionBrands = "",
                            PromotionCategory = "",
                            PromotionDiscount = "",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_196,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/46090f9c-e337-4a58-9d67-16bf4b977c6f1690787339358-Shop-By-Category_HP-4_32.jpg",
                            PromotionMainCategory = "",
                            PromotionSubCategory = "",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 48,
                            PromotionBrands = "",
                            PromotionCategory = "Bags & Backpacks",
                            PromotionDiscount = "30",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_196,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/89e0a0ee-225d-4880-a761-6aa895d252871690787338993-Shop-By-Category_HP-4_33.jpg",
                            PromotionMainCategory = "Men",
                            PromotionSubCategory = "",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 49,
                            PromotionBrands = "",
                            PromotionCategory = "Bags & Backpacks",
                            PromotionDiscount = "30",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_196,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/82cdf918-9ad9-41fa-a5a7-c4c86fbad90c1690787338876-Shop-By-Category_HP-4_34.jpg",
                            PromotionMainCategory = "",
                            PromotionSubCategory = "",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 50,
                            PromotionBrands = "",
                            PromotionCategory = "Footwear",
                            PromotionDiscount = "30",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_196,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/ed2e98bc-e4f4-4e85-bc74-537142205d0f1690787339374-Shop-By-Category_HP-4_35.jpg",
                            PromotionMainCategory = "Men",
                            PromotionSubCategory = "Flip Flops",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 51,
                            PromotionBrands = "",
                            PromotionCategory = "",
                            PromotionDiscount = "",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_196,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/c61b51c7-67cb-4d02-9f50-3492d08c0bba1690787339256-Shop-By-Category_HP-4_36.jpg",
                            PromotionMainCategory = "",
                            PromotionSubCategory = "",
                            PromotionType = "SHOP BY CATEGORY"
                        },
                        new
                        {
                            PromoionId = 52,
                            PromotionBrands = "",
                            PromotionCategory = "",
                            PromotionDiscount = "",
                            PromotionImage = "https://assets.myntassets.com/f_webp,w_196,c_limit,fl_progressive,dpr_2.0/assets/images/2023/7/31/c61b51c7-67cb-4d02-9f50-3492d08c0bba1690787339256-Shop-By-Category_HP-4_36.jpg",
                            PromotionMainCategory = "",
                            PromotionSubCategory = "",
                            PromotionType = "SHOP BY CATEGORY"
                        });
                });

            modelBuilder.Entity("myntra_clone_api.Models.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCategoryId"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubCategoryId");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("myntra_clone_api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("myntra_clone_api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("myntra_clone_api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("myntra_clone_api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
